language: python
python:
    - "2.6"
    - "2.7"
    - "3.2"
    - "3.3"
    - "pypy"

install:
    - pip install -q -r requirements.txt --use-mirrors
    - pip install -q --use-mirrors pep8

script:
    - ./tests/manage.py test RandoAmisSecours
    - pep8 --statistics RandoAmisSecours
